const fs = require('fs');
const { validateUrl } = require('../../lib/validation');
const { downloadToTemp, cleanup } = require('../../lib/media');

module.exports.config = { maxDuration: 300 };

module.exports = async (req, res) => {
  if (req.method !== 'GET') return res.status(405).json({ success: false, error: 'Method not allowed.' });

  const requestUrl = new URL(req.url, `https://${req.headers.host || 'localhost'}`);
  const sourceUrl = requestUrl.searchParams.get('url') || '';
  const formatId = requestUrl.searchParams.get('format') || 'best';
  const entry = requestUrl.searchParams.get('entry');

  const check = validateUrl(sourceUrl);
  if (!check.valid) return res.status(400).json({ success: false, error: check.error });

  // Allow only selectors generated by /api/analyze. Do not accept arbitrary yt-dlp expressions.
  const youtubeSelector = /^bestvideo\[height=\d{2,5}\]\+bestaudio\/best\[height=\d{2,5}\]$/;
  const freeYouTubeSelector = /^fyt:(piped|inv):\d+:(video|format):\d+$/;
  const instagramFormat = /^[A-Za-z0-9._-]{1,80}$/;
  if (!youtubeSelector.test(formatId) && !freeYouTubeSelector.test(formatId) && !instagramFormat.test(formatId) && formatId !== 'best') {
    return res.status(400).json({ success: false, error: 'Invalid format selection.' });
  }

  try {
    const result = await downloadToTemp(sourceUrl, formatId, entry ? Number(entry) : null);
    const stat = fs.statSync(result.filePath);

    res.statusCode = 200;
    res.setHeader('Content-Type', contentType(result.filePath));
    res.setHeader('Content-Length', String(stat.size));
    res.setHeader('Content-Disposition', `attachment; filename*=UTF-8''${encodeURIComponent(result.filename)}`);
    res.setHeader('Cache-Control', 'no-store, max-age=0');
    res.setHeader('X-Content-Type-Options', 'nosniff');

    const stream = fs.createReadStream(result.filePath);
    const cleanupOnce = () => cleanup(result.dir);
    stream.on('error', (err) => {
      console.error('[Eomeg download stream]', err);
      cleanupOnce();
      if (!res.headersSent) res.status(500).json({ success: false, error: 'Download stream failed.' });
      else res.end();
    });
    res.on('close', cleanupOnce);
    res.on('finish', cleanupOnce);
    stream.pipe(res);
  } catch (error) {
    console.error('[Eomeg download]', error);
    const code = error?.code;
    const status = code === 'CAROUSEL_SELECTION_REQUIRED' ? 409 : code === 'OUTPUT_TOO_LARGE' ? 413 : 502;
    return res.status(status).json({ success: false, error: friendlyError(error, sourceUrl) });
  }
};

function contentType(file) {
  const ext = file.toLowerCase().split('.').pop();
  return ({
    mp4: 'video/mp4', webm: 'video/webm', mkv: 'video/x-matroska',
    jpg: 'image/jpeg', jpeg: 'image/jpeg', png: 'image/png', webp: 'image/webp',
    mp3: 'audio/mpeg', m4a: 'audio/mp4', wav: 'audio/wav'
  })[ext] || 'application/octet-stream';
}

function friendlyError(error, url) {
  const msg = String(error?.stderr || error?.message || '');
  if (error?.code === 'FREE_YOUTUBE_FAILED') {
    return 'The free public YouTube extraction services are temporarily unavailable. Please try again in a few seconds.';
  }
  if (error?.code === 'CAROUSEL_SELECTION_REQUIRED') return error.message;
  if (error?.code === 'OUTPUT_TOO_LARGE') return error.message;

  if (/sign in to confirm.*not a bot|LOGIN_REQUIRED/i.test(msg) && /youtube\.com|youtu\.be/i.test(url)) {
    return 'Free YouTube extraction services are temporarily unavailable, and direct extraction from this Vercel server is being blocked by YouTube. Please try again shortly.';
  }

  if (/this video is private|private video|members-only|login required for this video|age.?restricted/i.test(msg)) {
    return 'This media requires access that this server does not have.';
  }

  if (/unsupported|not a valid url/i.test(msg)) return 'This URL is not currently supported.';
  if (/timeout|timed out/i.test(msg)) return 'The download took too long. Try a shorter or lower-quality version.';
  return 'We could not download this media. Please try again.';
}
